# clés SonarCloud
sonar.projectKey=Mathys-V_Bomberman-arena
sonar.organization=mathys-v-github

# Dossiers à analyser
sonar.sources=client,server

# Fichiers à ignorer
sonar.exclusions=**/node_modules/**, **/*.test.js

sonar.sourceEncoding=UTF-8