name: Pipeline CI Bomberman

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  qualite-serveur:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Installation des dépendances Serveur
        working-directory: ./server
        run: npm install

      - name: Vérification du style (Linting)
        working-directory: ./server
        run: npx eslint .

  qualite-client:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Installation des dépendances Client
        working-directory: ./client
        run: npm install

      - name: Vérification du style (Linting)
        working-directory: ./client
        run: npx eslint .
